tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#fd9a12",
        "surface-dim": "#dadadc",
        secondary: "#006e2b",
        "on-tertiary-fixed": "#2c1600",
        "primary-fixed": "#b2ecfa",
        "on-secondary-container": "#00752e",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfc8ca",
        "primary-fixed-dim": "#96d0de",
        background: "#faf9fb",
        tertiary: "#462600",
        "tertiary-fixed": "#ffdcbd",
        outline: "#70787b",
        "inverse-surface": "#2f3032",
        "tertiary-container": "#653a00",
        "secondary-fixed-dim": "#63df7a",
        error: "#ba1a1a",
        "surface-container": "#eeedf0",
        "on-secondary-fixed": "#002108",
        "on-background": "#1a1c1d",
        "on-error-container": "#93000a",
        "on-primary-container": "#81bac8",
        surface: "#faf9fb",
        "on-primary-fixed": "#001f25",
        "tertiary-fixed-dim": "#ffb86e",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f0f2",
        "surface-bright": "#faf9fb",
        "inverse-primary": "#96d0de",
        "on-surface": "#1a1c1d",
        "on-tertiary-fixed-variant": "#693c00",
        "secondary-fixed": "#80fc93",
        primary: "#00333c",
        "surface-tint": "#2a6673",
        "on-primary": "#ffffff",
        "surface-container-high": "#e8e8ea",
        "primary-container": "#004b57",
        "on-primary-fixed-variant": "#064e5a",
        "secondary-container": "#80fc93",
        "surface-variant": "#e3e2e4",
        "surface-container-highest": "#e3e2e4",
        "surface-container-low": "#f4f3f5",
        "on-surface-variant": "#40484a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#00531e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        "grid-gutter": "16px",
        sm: "8px",
        "grid-margin": "24px",
        xl: "32px",
        md: "16px",
        base: "4px",
        lg: "24px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-md": ["Inter"],
        "headline-lg": ["Manrope"],
      },
      fontSize: {
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.02em",
            fontWeight: "600",
          },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
};
